
create table netology.ORDERS
(
    id int generated by default as identity primary key,
    date timestamp not null,
    customer_id int,
    product_name varchar not null,
    amount int not null,
    foreign key (customer_id) references netology.CUSTOMERS(id)
);

insert into netology.ORDERS (date, customer_id, product_name, amount)
VALUES ('05.09.2024', 1, 'apples', 100)
('04.09.2024', 2, 'lemons', 200)
('03.09.2024', 3, 'peaches', 300)
('02.09.2024', 4, 'pears', 400)
('01.09.2024', 5, 'orange', 500);